### ISSUE TITLE
Container image analysis scenario fails

### ISSUE THREAD

**Issue by fridex** [thoth-station/integration-tests#128]
**Describe the bug**

```
When I trigger container image analysis for registry.access.redhat.com/ubi8/ubi-minimal:latest with force set to 1 (4.195s)

Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/behave/model.py", line 1329, in run
    match.run(runner.context)
  File "/opt/app-root/lib64/python3.8/site-packages/behave/matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "features/steps/image_analysis.py", line 73, in step_impl
    assert "terminated" in status
TypeError: argument of type 'int' is not iterable
```

**To Reproduce**

This applies to stage and test environment.

**Expected behavior**

Container image analysis should be successful.

**Screenshots**

**Additional context**

**Comment by fridex** [comment]
The issue is caused by schema validation, the response is not valid:

```
{
  "detail": "'finished_at' is a required property\n\nFailed validating 'required' in schema['properties']['status']:\n    {'description': 'Status information about the analysis run.',\n     'properties': {'finished_at': {'description': 'Datetime in ISO format '\n                                                   'informing about when '\n                                                   'the analysis has '\n                                                   'finished.\\n',\n                                    'nullable': True,\n                                    'type': 'string'},\n                    'reason': {'description': 'Reasoning on finished run.',\n                               'nullable': True,\n                               'type': 'string'},\n                    'started_at': {'description': 'Datetime in ISO format '\n                                                  'informing about when '\n                                                  'the analysis has '\n                                                  'started.\\n',\n                                   'nullable': True,\n                                   'type': 'string'},\n                    'state': {'example': 'running', 'type': 'string'}},\n     'required': ['finished_at', 'reason', 'started_at', 'state'],\n     'type': 'object'}\n\nOn instance['status']:\n    {'terminated': {'containerID': 'cri-o://98444da3c5a529f95dfb825fbebdf1629bd4ef094ce6c02ef7ef3c28b82a50e7',\n                    'exitCode': 0,\n                    'finishedAt': '2021-02-18T09:26:21Z',\n                    'reason': 'Completed',\n                    'startedAt': '2021-02-18T09:25:54Z'}}",
  "status": 500,
  "title": "Response body does not conform to specification",
  "type": "about:blank"
}
```

```
Failed validating 'required' in schema['properties']['status']:
    {'description': 'Status information about the analysis run.',
     'properties': {'finished_at': {'description': 'Datetime in ISO format '
                                                   'informing about when '
                                                   'the analysis has '
                                                   'finished.\n',
                                    'nullable': True,
                                    'type': 'string'},
                    'reason': {'description': 'Reasoning on finished run.',
                               'nullable': True,
                               'type': 'string'},
                    'started_at': {'description': 'Datetime in ISO format '
                                                  'informing about when '
                                                  'the analysis has '
                                                  'started.\n',
                                   'nullable': True,
                                   'type': 'string'},
                    'state': {'example': 'running', 'type': 'string'}},
     'required': ['finished_at', 'reason', 'started_at', 'state'],
     'type': 'object'}

On instance['status']:
    {'terminated': {'containerID': 'cri-o://98444da3c5a529f95dfb825fbebdf1629bd4ef094ce6c02ef7ef3c28b82a50e7',
                    'exitCode': 0,
                    'finishedAt': '2021-02-18T09:26:21Z',
                    'reason': 'Completed',
                    'startedAt': '2021-02-18T09:25:54Z'}}
```

**Comment by fridex** [comment]
Fix in https://github.com/thoth-station/common/pull/1113 thoth-common with the fix needs to be propagated to user-api to fix this.
