### ISSUE TITLE
Submitting to amun fails in test

### ISSUE THREAD

**Issue by fridex** [thoth-station/integration-tests#129]
**Describe the bug**

```
When an amun inspection job is scheduled (1.204s)

Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/behave/model.py", line 1329, in run
    match.run(runner.context)
  File "/opt/app-root/lib64/python3.8/site-packages/behave/matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "features/steps/amun_api.py", line 92, in amun_schedule
    api_response = api_instance.post_inspection(specification)
  File "/opt/app-root/lib64/python3.8/site-packages/amun/swagger_client/amun/inspection_api.py", line 713, in post_inspection
    return self.post_inspection_with_http_info(inspection_specification, **kwargs)  # noqa: E501
  File "/opt/app-root/lib64/python3.8/site-packages/amun/swagger_client/amun/inspection_api.py", line 785, in post_inspection_with_http_info
    return self.api_client.call_api(
  File "/opt/app-root/lib64/python3.8/site-packages/amun/swagger_client/api_client.py", line 338, in call_api
    return self.__call_api(resource_path, method,
  File "/opt/app-root/lib64/python3.8/site-packages/amun/swagger_client/api_client.py", line 170, in __call_api
    response_data = self.request(
  File "/opt/app-root/lib64/python3.8/site-packages/amun/swagger_client/api_client.py", line 381, in request
    return self.rest_client.POST(url,
  File "/opt/app-root/lib64/python3.8/site-packages/amun/swagger_client/rest.py", line 270, in POST
    return self.request("POST", url,
  File "/opt/app-root/lib64/python3.8/site-packages/amun/swagger_client/rest.py", line 229, in request
    raise ApiException(http_resp=r)
amun.swagger_client.exceptions.ApiException: (500)
Reason: INTERNAL SERVER ERROR
HTTP response headers: HTTPHeaderDict({'Server': 'gunicorn/20.0.4', 'Date': 'Thu, 18 Feb 2021 00:00:54 GMT', 'Content-Type': 'application/json', 'Content-Length': '177', 'X-Amun-Version': '0.9.2+storage.0.36.0.common.0.23.0', 'Access-Control-Allow-Origin': '*', 'Set-Cookie': '86f7dd5a59fa5933063a93e017e28dbc=d1e0e46de6501c08322e1fd8e1031f16; path=/; HttpOnly; Secure; SameSite=None'})
HTTP response body: {"details":{"datetime":"2021-02-18T00:00:54.565519","type":"InternalServerError"},"error":"Internal server error occurred, please contact administrator with provided details."}
```

**To Reproduce**

Run integration-tests against test environment.

**Comment by fridex** [comment]
Looks like readiness is failing often:

``
Readiness probe failed: Get "http://172.20.8.198:8080/readiness": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**Comment by fridex** [comment]
Amun API looks more stable now. I will close this.
