### ISSUE TITLE
Some advise integration tests fail cloning repo

### ISSUE THREAD

**Issue by fridex** [thoth-station/integration-tests#254]
**Describe the bug**

See errors from integration-tests reports:

```
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/behave/model.py", line 1329, in run
    match.run(runner.context)
  File "/opt/app-root/lib64/python3.8/site-packages/behave/matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "features/steps/advise.py", line 214, in step_impl
    context.repo = git.Repo.clone_from(git_repo, tempfile.mkdtemp(), depth=1)
  File "/opt/app-root/lib64/python3.8/site-packages/git/repo/base.py", line 1148, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, multi_options, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/git/repo/base.py", line 1086, in _clone
    finalize_process(proc, stderr=stderr)
  File "/opt/app-root/lib64/python3.8/site-packages/git/util.py", line 386, in finalize_process
    proc.wait(**kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/git/cmd.py", line 502, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(-9)
  cmdline: git clone -v --depth=1 https://github.com/thoth-station/elyra-aidevsecops-tutorial /tmp/tmp66xu8i82
  stderr: 'Cloning into '/tmp/tmp66xu8i82'...
POST git-upload-pack (192 bytes)
POST git-upload-pack (201 bytes)
'
```

**Comment by mayaCostantini** [comment]
For what deployment does this error happen? I ran the test on stage and the errors I get are related to the OpenAPI schema which has not been updated yet, but the `elyra-aidevsecops-tutorial` was cloned successfully.

**Comment by fridex** [comment]
I took the error message from the e-mail report - `Integration tests update for ocp4-stage (2022-02-23 version 0.9.1)`

**Comment by goern** [comment]
is this still valid? @fridex @mayaCostantini

**Comment by mayaCostantini** [comment]
@goern I don't see this issue anymore in stage reports so this should be good, @fridex wdyt?

**Comment by fridex** [comment]
Yes, we can close this.

/close
