### ISSUE TITLE
ocp-ci-analysis fail in integration tests

### ISSUE THREAD

**Issue by fridex** [thoth-station/integration-tests#255]
**Describe the bug**

```
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/python/project.py", line 82, in from_files
    pipfile = Pipfile.from_file(pipfile_path)
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/python/pipfile.py", line 393, in from_file
    return cls.from_string(pipfile_file.read())
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/python/pipfile.py", line 408, in from_string
    return cls.from_dict(parsed)
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/python/pipfile.py", line 422, in from_dict
    packages=Packages.from_pipfile(packages, develop=False, meta=meta),
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/python/packages.py", line 90, in from_pipfile
    package_version[package_name] = PackageVersion.from_pipfile_entry(package_name, package_info, develop, meta)
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/python/package_version.py", line 449, in from_pipfile_entry
    raise UnsupportedConfigurationError(
thoth.python.exceptions.UnsupportedConfigurationError: Package 'src' does not state any version range specifier: {'path': '.'}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/behave/model.py", line 1329, in run
    match.run(runner.context)
  File "/opt/app-root/lib64/python3.8/site-packages/behave/matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "features/steps/advise.py", line 244, in step_impl
    project = Project.from_files(
  File "/opt/app-root/lib64/python3.8/site-packages/thoth/python/project.py", line 84, in from_files
    raise FileLoadError(
thoth.python.exceptions.FileLoadError: Failed to load Pipfile (path: /tmp/tmp261bs6ts/Pipfile: Package 'src' does not state any version range specifier: {'path': '.'}
```

This is caused by `src` installation in the pipfile:

https://github.com/aicoe-aiops/ocp-ci-analysis/blob/d875c8715f175d9e0619876e550f98bcb464524d/Pipfile#L35

**Comment by goern** [comment]
is this still valide? @fridex
