### ISSUE TITLE
Integration tests raise an exception at the end

### ISSUE THREAD

**Issue by fridex** [thoth-station/integration-tests#265]
**Describe the bug**

```
Exception ignored in: <function ApiClient.__del__ at 0x7f7ea37c1ca0>
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
  File "/usr/lib64/python3.8/multiprocessing/pool.py", line 649, in close
    self._change_notifier.put(None)
  File "/usr/lib64/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 204, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 415, in _send_bytes
    self._send(header + buf)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 372, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function ApiClient.__del__ at 0x7f7ea37c1ca0>
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
  File "/usr/lib64/python3.8/multiprocessing/pool.py", line 649, in close
    self._change_notifier.put(None)
  File "/usr/lib64/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 204, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 415, in _send_bytes
    self._send(header + buf)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 372, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function ApiClient.__del__ at 0x7f7ea37c1ca0>
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
  File "/usr/lib64/python3.8/multiprocessing/pool.py", line 649, in close
    self._change_notifier.put(None)
  File "/usr/lib64/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 204, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 415, in _send_bytes
    self._send(header + buf)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 372, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function ApiClient.__del__ at 0x7f7ea37c1ca0>
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
  File "/usr/lib64/python3.8/multiprocessing/pool.py", line 649, in close
    self._change_notifier.put(None)
  File "/usr/lib64/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 204, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 415, in _send_bytes
    self._send(header + buf)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 372, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function ApiClient.__del__ at 0x7f7ea37c1ca0>
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
  File "/usr/lib64/python3.8/multiprocessing/pool.py", line 649, in close
    self._change_notifier.put(None)
  File "/usr/lib64/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 204, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 415, in _send_bytes
    self._send(header + buf)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 372, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function ApiClient.__del__ at 0x7f7ea37c1ca0>
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
  File "/usr/lib64/python3.8/multiprocessing/pool.py", line 649, in close
    self._change_notifier.put(None)
  File "/usr/lib64/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 204, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 415, in _send_bytes
    self._send(header + buf)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 372, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function ApiClient.__del__ at 0x7f7ea37c1ca0>
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
  File "/usr/lib64/python3.8/multiprocessing/pool.py", line 649, in close
    self._change_notifier.put(None)
  File "/usr/lib64/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 204, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 415, in _send_bytes
    self._send(header + buf)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 372, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function ApiClient.__del__ at 0x7f7ea37c1ca0>
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
  File "/usr/lib64/python3.8/multiprocessing/pool.py", line 649, in close
    self._change_notifier.put(None)
  File "/usr/lib64/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 204, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 415, in _send_bytes
    self._send(header + buf)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 372, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function ApiClient.__del__ at 0x7f7ea37c1ca0>
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
  File "/usr/lib64/python3.8/multiprocessing/pool.py", line 649, in close
    self._change_notifier.put(None)
  File "/usr/lib64/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 204, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 415, in _send_bytes
    self._send(header + buf)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 372, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function ApiClient.__del__ at 0x7f7ea37c1ca0>
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
  File "/usr/lib64/python3.8/multiprocessing/pool.py", line 649, in close
    self._change_notifier.put(None)
  File "/usr/lib64/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 204, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 415, in _send_bytes
    self._send(header + buf)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 372, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function ApiClient.__del__ at 0x7f7ea37c1ca0>
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
  File "/usr/lib64/python3.8/multiprocessing/pool.py", line 649, in close
    self._change_notifier.put(None)
  File "/usr/lib64/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 204, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 415, in _send_bytes
    self._send(header + buf)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 372, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function ApiClient.__del__ at 0x7f7ea37c1ca0>
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
  File "/usr/lib64/python3.8/multiprocessing/pool.py", line 649, in close
    self._change_notifier.put(None)
  File "/usr/lib64/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 204, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 415, in _send_bytes
    self._send(header + buf)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 372, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function ApiClient.__del__ at 0x7f7ea37c1ca0>
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
  File "/usr/lib64/python3.8/multiprocessing/pool.py", line 649, in close
    self._change_notifier.put(None)
  File "/usr/lib64/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 204, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 415, in _send_bytes
    self._send(header + buf)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 372, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function ApiClient.__del__ at 0x7f7ea37c1ca0>
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
  File "/usr/lib64/python3.8/multiprocessing/pool.py", line 649, in close
    self._change_notifier.put(None)
  File "/usr/lib64/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 204, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 415, in _send_bytes
    self._send(header + buf)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 372, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function ApiClient.__del__ at 0x7f7ea37c1ca0>
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
  File "/usr/lib64/python3.8/multiprocessing/pool.py", line 649, in close
    self._change_notifier.put(None)
  File "/usr/lib64/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 204, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 415, in _send_bytes
    self._send(header + buf)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 372, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function ApiClient.__del__ at 0x7f7ea37c1ca0>
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
  File "/usr/lib64/python3.8/multiprocessing/pool.py", line 649, in close
    self._change_notifier.put(None)
  File "/usr/lib64/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 204, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 415, in _send_bytes
    self._send(header + buf)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 372, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function ApiClient.__del__ at 0x7f7ea37c1ca0>
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
  File "/usr/lib64/python3.8/multiprocessing/pool.py", line 649, in close
    self._change_notifier.put(None)
  File "/usr/lib64/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 204, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 415, in _send_bytes
    self._send(header + buf)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 372, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function ApiClient.__del__ at 0x7f7ea37c1ca0>
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
  File "/usr/lib64/python3.8/multiprocessing/pool.py", line 649, in close
    self._change_notifier.put(None)
  File "/usr/lib64/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 204, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 415, in _send_bytes
    self._send(header + buf)
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 372, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
```

**Comment by mayaCostantini** [comment]
Not sure if this helps, but I found a related issue in the `swagger-codegen` repository: https://github.com/swagger-api/swagger-codegen/issues/6392, which was supposed to be fixed by the following PR: https://github.com/swagger-api/swagger-codegen/pull/6396.

However, this more recent issue: https://github.com/swagger-api/swagger-codegen/issues/9991 mentions that Python 3.8 does not support cleaning pools using the methods in the `ApiClient` destructor implementation. Other issues in the `swagger-codegen` repo and in referenced issues from other projects also seem to indicate a Python 3.8 bug.

**Comment by fridex** [comment]
This is not impacting users, nice to have and worth checking what is wrong here.

/priority important-soon
