### ISSUE TITLE
thamos.exceptions.TimeoutError: Thoth backend did not respond in time

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/integration-tests#273]
**Describe the bug**
The following error occurred for adviser tests on the `Run thamos advise on a Git repo -- @1.10 Advise` scenario:

```
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/behave/model.py", line 1329, in run
    match.run(runner.context)
  File "/opt/app-root/lib64/python3.8/site-packages/behave/matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "features/steps/advise.py", line 251, in step_impl
    results = advise_using_config(
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/lib.py", line 399, in advise_using_config
    return advise(
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/lib.py", line 118, in wrapper
    result = func(api_client, *args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/lib.py", line 591, in advise
    _wait_for_analysis(
  File "/opt/app-root/lib64/python3.8/site-packages/thamos/lib.py", line 205, in _wait_for_analysis
    raise TimeoutError(
thamos.exceptions.TimeoutError: Thoth backend did not respond in time, timeout set to 2000 - see https://thoth-station.ninja/j/thamos_timeout

Captured stdout:
{'host': 'stage.thoth-station.ninja', 'tls_verify': True, 'requirements_format': 'pipenv', 'overlays_dir': 'overlays', 'runtime_environments': [{'name': 'ps-cv-ocr', 'operating_system': {'name': 'ubi', 'version': '8'}, 'python_version': '3.8', 'recommendation_type': 'latest'}, {'name': 'ps-cv-pytorch', 'operating_system': {'name': 'ubi', 'version': '8'}, 'python_version': '3.8', 'recommendation_type': 'latest'}, {'name': 'ps-cv-tensorflow', 'operating_system': {'name': 'ubi', 'version': '8'}, 'python_version': '3.8', 'recommendation_type': 'latest'}], 'managers': [{'name': 'info'}, {'name': 'version', 'configuration': {'maintainers': ['goern', 'harshad16', 'pacospace'], 'assignees': ['sesheta'], 'labels': ['bot'], 'changelog_file': True}}, {'name': 'thoth-advise', 'configuration': {'labels': ['bot']}}]}

Captured logging:
INFO:thamos.lib:Using 'latest' recommendation type - see https://thoth-station.ninja/recommendation-types/
WARNING:thamos.lib:The user stack found in the lock file will not be supplied as requested
INFO:thamos.lib:Successfully submitted advise analysis 'adviser-220301101029-7c2aa8c75a36538f' to 'https://stage.thoth-station.ninja/api/v1'
```

**To Reproduce**
See last integration tests report (`Integration tests update for ocp4-stage (2022-03-01 version 0.9.2)` at 1:03PM CEST)

**Comment by fridex** [comment]
I don't see this issue in reports anymore. It looks like https://github.com/thoth-station/thamos/pull/1066 fix the issue.

/close
