### ISSUE TITLE
Fail to check for minimum solvers available in aws-prod

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/integration-tests#337]
**Describe the bug**

From Integration tests update for aws-prod (2022-09-12 version 0.11.3):

```
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/behave/model.py", line 1329, in run
    match.run(runner.context)
  File "/opt/app-root/lib64/python3.8/site-packages/behave/matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "features/steps/solvers.py", line 43, in step_impl
    assert entry in context.result["environment"], context.result
KeyError: 'environment'
```

**Comment by harshad16** [comment]
Verified this.
The content exists on the API: `https://api.moc.thoth-station.ninja/api/v1/python/environment`
and the integration-tests instance seems to be working.
```
Feature: Check for minimum solvers available in Thoth # features/solvers.feature:1

  @solvers
  Scenario: Check there are minimum solvers available in Thoth   # features/solvers.feature:3
    Given deployment is accessible using HTTPS                   # features/steps/common.py:26 0.775s
    When we ask for the available solvers                        # features/steps/solvers.py:46 0.417s
    Then they should include at least the minimum set of solvers # features/steps/solvers.py:55 0.000s
```

seems like this would have happen, when user-api lost connection to PostgreSQL db.
for now it seems to be fixed.
closing this.
